# config.yaml
price : 2000
scheduleNo : "100002"
#预售是ST0002,公售为ST0001
sellTypeCode: "ST0001"
prodId: "211541"
openProxy: 1
proxy:	"http://127.0.0.1:7890"
email: "1140255845@qq.com"
pwd: "Ly052943918@"
#email: "micky06041207@gmail.com"
#pwd: "19910923key"
melonCookie: 'MAC_T="gPRm3u5hfig2V5w7NLViW0rrEznyrl0lcOpeysjjx3TFBT0LQogZ07FuVwOQZWimZq4dRF681kKPCyeQCZZrrg=="; keyCookie_T=1001141433; _fwb=17ZVbicrtmLsAu911KcdrC.1755684970300; PCID=17556849703089033306180; TKT_POC_ID=WP19; i18next=EN; NetFunnel_ID=WP15; JSESSIONID=779FA8942370868B2AF252F6FFDBFA90; wcs_bt=s_322bdbd6fd48:1755763861'
inicsCookie:  "Er6EdZabr1K9IaX740Ao6xOd65qIg8DE28aAe4X89tsKIWlazVozb9ZubZQw6kaq.bnN0ZHBheV9kb21haW4vbnN0ZHBheTItc2VydmVyMQ=="
key: ""
#13024516491
tel:  "13055253090"
fdsWdata: "X5Em+wvO3ctCITrAt368w7Kmo3VgBXDMrPgBrleXnu6osH5keE5m5wvaaN2lko3FLb+Pmm8HCmP5+wbJS5f6+eNbzPVS60eq7BVgnMNBvBxkqKsmjkDX4CslAYbJl9qTGiTuQLJbMGCqWtbguXBhmDP3GF+ej3EcyxDMgGFeA6jHRXWHe1Vx/bHlLqyAehucT/ag6Yrv5cLTBM+xpLf+qsX9LWplW8yRIgMDGz8WifIZ6CvN35KqJz/bhnmb13Wm/T6Dgb6Q3nzrYl9g3XC2fDtiew2chVJExmR42PQuyVjFoeurTe8zsPUz47LqyTJbOTjXNdfGCJBLKYfpiIP4gzM/QyEVLhWNTI2pJwyw8LGyV61ozkmOed+ENQEp4MgmKvXwn8eyLBC/k++RP8Id3ak5zE/rHJnkB7M8O8spixOSGKDpt3hAHNUjDPR40jmLs19nAbQO8fioHVx0hv9MrXNH1Yee/1NDrSrLxrc9tAzRyhVPbITfaWDqGArpYvVy7CQWgBdlqRggCgSkydmTY4T0LNuo2pWCRXUReQBczBZg0RTfPbo8flZ0ipNfJzyuTuJUB15LjUyJSsqDGBofR3OduNgfFoHRCz6ftkoLPQAbWLyN1TyR6S7VGwqwTpVj5wb652rfnSBsPJPebqoUW15MO7xyg4BOk+X6eY/f+PajfTpbhhIB/Ox6zRmiGz9d4Gt6jn6sKcRljVCgZkhnZZT021zkTJnN4rS83FWjVUwYzMqHzkTFaHoAZMmtKLtW58nr8zGWv2IsyilCTL2UjJzJBwlAOPeaT02pl4D0iCgjkRFzYWxTULvrgJlf4l00gcZ6bPTZrF+pxHdHS3bJL7Lg3TdL5wydrLlQdXD2pjwGFFkAIw8KbixHtV7X1vsP4/mfqSOSJz4zBue+6RLIi6RuF+h/jdf25cZvBi2/5ekjXoYMXQ7HnhPwltjXm+QJ3EG8hbBUxPMR7F/bpkQFzR4Jxe5QAU8iYgSa9XisgYxak+AaN5H772Wv5JDWJZozY7CjaLc8bjMPxTc9TLH/LQ3xJ2ZNQVH5ozstUg/3XfAF9kUNCl3y58ss4sSU98QcfOJ2Uz0G4LJr/cJMFqy0i1XHYsyQBzHurWkGvXc0CFIF/YNye0wnzXi+Nw5zSIzxQbnUQp2dFARh9k8o6tvp5dcUEX1YmLaatqUx8z8mEgUPCcUVBdP7dMR1PHWNrCUYumrdKFr7ehIrkNarfEXhggta8DH4p9yPOOKYMbAsAAR7xY0GDhKr/rc1GmSAcyAJ2d+ipYI4cwBVGMFSEZFfmrpCPBqFPT+FBSq1KN4kXmSM7A585NjihgOnXkyoNgUpCT1g56np2l+4WQocDMnzuvLC+czyN7Z5"
fdsUkey:  "a0438146-a356-4b1e-9947-71ce31d721c5"

minio:
  endpoint: "124.222.28.99:9000"
  accessKeyID: "0jJuYou9de8ZfvkqtarQ"
  secretAccessKey: "RpsHHtpC9ezsKlEzycTXBp"

areaNos: "10,11,34"
